# Generated by Django 5.0.1 on 2024-12-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_updated_at_profile_location_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='school',
        ),
    ]
