# Generated by Django 5.0.1 on 2024-12-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_child_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='school',
        ),
    ]
