[build]
  command = "npm i && pip install --upgrade pip setuptools wheel && pip install -r requirements.txt && pip install gunicorn && python manage.py migrate && python manage.py collectstatic --noinput"
  publish = "static"

[build.environment]
  PYTHON_VERSION = "3.10"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200