# Generated by Django 5.0.1 on 2024-12-12 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='borders',
            new_name='boarders',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='last_change_date',
            new_name='last_changed_date',
        ),
    ]
