# Generated by Django 5.0.1 on 2024-12-12 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_rename_borders_school_boarders_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='ofstead_special_measures',
            new_name='ofsted_special_measures',
        ),
    ]
