# Generated by Django 5.0.1 on 2024-12-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_school_urn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uprn',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='urn',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
