# Generated by Django 5.0.1 on 2024-12-12 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_alter_school_uprn_alter_school_urn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='school',
            name='updated_at',
        ),
    ]
