# Generated by Django 5.0.1 on 2024-12-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_remove_school_created_at_remove_school_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
