# Generated by Django 5.0.1 on 2024-12-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_alter_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='urn',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
