# Generated by Django 5.0.1 on 2024-12-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_alter_school_urn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='school',
            name='urn',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
