# Generated by Django 5.0.1 on 2024-12-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_auto_20241214_1305'),
        ('schools', '0012_auto_20241214_1309'),
    ]

    operations = [
    ]
