# Generated by Django 5.0.1 on 2024-12-14 13:44
from django.db import migrations, models
import uuid

def generate_uuid(apps, schema_editor):
    School = apps.get_model('schools', 'School')
    for school in School.objects.all():
        school.new_id = uuid.uuid4()
        school.save()

class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_auto_20241214_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(generate_uuid),
        migrations.AlterField(
            model_name='school',
            name='new_id',
            field=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False),
        ),
        migrations.RemoveField(
            model_name='school',
            name='id',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='new_id',
            new_name='id',
        ),
    ]