# Generated by Django 5.0.1 on 2024-12-14 13:45

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_merge_0011_auto_20241214_1305_0012_auto_20241214_1309'),
        ('schools', '0014_auto_20241214_1344'),
    ]

    operations = [
    ]