# Generated by Django 5.0.1 on 2024-12-14 18:50

from django.db import migrations, models
import uuid

BATCH_SIZE = 1000

def generate_uuid(apps, schema_editor):
    School = apps.get_model('schools', 'School')
    total_records = School.objects.count()
    for start in range(0, total_records, BATCH_SIZE):
        end = min(start + BATCH_SIZE, total_records)
        schools = School.objects.order_by('id')[start:end]
        for school in schools:
            school.new_id = uuid.uuid4()
        School.objects.bulk_update(schools, ['new_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_merge_0016_alter_school_id_0017_auto_20241214_1845'),
    ]

    operations = [
        # Step 1: Add a new UUID column (not yet a primary key)
        migrations.AddField(
            model_name='school',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        # Step 2: Populate new_id with UUIDs
        migrations.RunPython(generate_uuid),
        # Step 3: Drop the primary key constraint on the old id column
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.IntegerField(),
        ),
        # Step 4: Remove the old id column
        migrations.RemoveField(
            model_name='school',
            name='id',
        ),
        # Step 5: Rename new_id to id and make it the primary key
        migrations.RenameField(
            model_name='school',
            old_name='new_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False),
        ),
    ]
