# Generated by Django 5.0.1 on 2024-12-14 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0019_alter_school_id'),
        ('schools', '0020_merge_20241214_1919'),
        ('schools', '0021_merge_0019_alter_school_id_0020_merge_20241214_1919'),
    ]

    operations = [
    ]
