# Generated by Django 5.0.1 on 2024-12-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0024_alter_school_options_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='vote_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
