# Generated by Django 5.0.1 on 2024-12-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0025_school_vote_ratio_school_vote_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['-vote_ratio', '-vote_total', 'establishment_name']},
        ),
    ]
